// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/organizations" | "/admin/users" | "/analytics" | "/claude-test" | "/dev-check" | "/gpt-research" | "/login" | "/markitdown-test" | "/notes/[id]" | "/org/api-keys" | "/org/users" | "/privacy" | "/productbacklog" | "/profile" | "/profile/api-keys" | "/research-summary" | "/signup" | "/terms" | "/w/[ws]" | "/w/[ws]/projects/[projectSlug]" | "/w/[ws]/search" | "/w/[ws]/visualize" | "/workspaces"
type AppRouteHandlerRoutes = "/api/admin/add-user" | "/api/admin/check-sessions" | "/api/admin/check-users" | "/api/admin/organizations" | "/api/admin/test-auth" | "/api/admin/test-session" | "/api/admin/users" | "/api/agent-mcp" | "/api/ai/chat" | "/api/analytics" | "/api/anonymize-preview" | "/api/auth/debug" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/signup" | "/api/claude-tool" | "/api/debug-permissions" | "/api/debug/fix-robert-access" | "/api/debug/workspace-access" | "/api/docs" | "/api/gpt" | "/api/invitations/[token]" | "/api/keys" | "/api/markitdown-test/convert" | "/api/mcp" | "/api/mcp-ai" | "/api/mcp-hosted" | "/api/mcp-server" | "/api/mcp/documents" | "/api/mcp/projects" | "/api/mcp/search" | "/api/mcp/test" | "/api/mcp/workspaces" | "/api/org/api-keys" | "/api/org/api-keys/[keyId]" | "/api/org/invitations" | "/api/org/users" | "/api/org/users/[userId]" | "/api/org/users/[userId]/role" | "/api/org/users/invite" | "/api/org/users/invite-link" | "/api/organizations" | "/api/profile" | "/api/test-db" | "/api/test-env" | "/api/test-password" | "/api/workspaces" | "/test-deploy" | "/w/[ws]/api/context" | "/w/[ws]/api/projects" | "/w/[ws]/api/projects/[projectSlug]" | "/w/[ws]/api/projects/[projectSlug]/documents" | "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]" | "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/favorite" | "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/rename" | "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags" | "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/[tag]" | "/w/[ws]/api/search" | "/w/[ws]/api/tags" | "/w/[ws]/api/users" | "/w/[ws]/api/workspace"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/organizations": {}
  "/admin/users": {}
  "/analytics": {}
  "/api/admin/add-user": {}
  "/api/admin/check-sessions": {}
  "/api/admin/check-users": {}
  "/api/admin/organizations": {}
  "/api/admin/test-auth": {}
  "/api/admin/test-session": {}
  "/api/admin/users": {}
  "/api/agent-mcp": {}
  "/api/ai/chat": {}
  "/api/analytics": {}
  "/api/anonymize-preview": {}
  "/api/auth/debug": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/signup": {}
  "/api/claude-tool": {}
  "/api/debug-permissions": {}
  "/api/debug/fix-robert-access": {}
  "/api/debug/workspace-access": {}
  "/api/docs": {}
  "/api/gpt": {}
  "/api/invitations/[token]": { "token": string; }
  "/api/keys": {}
  "/api/markitdown-test/convert": {}
  "/api/mcp": {}
  "/api/mcp-ai": {}
  "/api/mcp-hosted": {}
  "/api/mcp-server": {}
  "/api/mcp/documents": {}
  "/api/mcp/projects": {}
  "/api/mcp/search": {}
  "/api/mcp/test": {}
  "/api/mcp/workspaces": {}
  "/api/org/api-keys": {}
  "/api/org/api-keys/[keyId]": { "keyId": string; }
  "/api/org/invitations": {}
  "/api/org/users": {}
  "/api/org/users/[userId]": { "userId": string; }
  "/api/org/users/[userId]/role": { "userId": string; }
  "/api/org/users/invite": {}
  "/api/org/users/invite-link": {}
  "/api/organizations": {}
  "/api/profile": {}
  "/api/test-db": {}
  "/api/test-env": {}
  "/api/test-password": {}
  "/api/workspaces": {}
  "/claude-test": {}
  "/dev-check": {}
  "/gpt-research": {}
  "/login": {}
  "/markitdown-test": {}
  "/notes/[id]": { "id": string; }
  "/org/api-keys": {}
  "/org/users": {}
  "/privacy": {}
  "/productbacklog": {}
  "/profile": {}
  "/profile/api-keys": {}
  "/research-summary": {}
  "/signup": {}
  "/terms": {}
  "/test-deploy": {}
  "/w/[ws]": { "ws": string; }
  "/w/[ws]/api/context": { "ws": string; }
  "/w/[ws]/api/projects": { "ws": string; }
  "/w/[ws]/api/projects/[projectSlug]": { "ws": string; "projectSlug": string; }
  "/w/[ws]/api/projects/[projectSlug]/documents": { "ws": string; "projectSlug": string; }
  "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]": { "ws": string; "projectSlug": string; "documentId": string; }
  "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/favorite": { "ws": string; "projectSlug": string; "documentId": string; }
  "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/rename": { "ws": string; "projectSlug": string; "documentId": string; }
  "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags": { "ws": string; "projectSlug": string; "documentId": string; }
  "/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/[tag]": { "ws": string; "projectSlug": string; "documentId": string; "tag": string; }
  "/w/[ws]/api/search": { "ws": string; }
  "/w/[ws]/api/tags": { "ws": string; }
  "/w/[ws]/api/users": { "ws": string; }
  "/w/[ws]/api/workspace": { "ws": string; }
  "/w/[ws]/projects/[projectSlug]": { "ws": string; "projectSlug": string; }
  "/w/[ws]/search": { "ws": string; }
  "/w/[ws]/visualize": { "ws": string; }
  "/workspaces": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
