// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizations">> = Specific
  const handler = {} as typeof import("../../app/admin/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/claude-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claude-test">> = Specific
  const handler = {} as typeof import("../../app/claude-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-check">> = Specific
  const handler = {} as typeof import("../../app/dev-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gpt-research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gpt-research">> = Specific
  const handler = {} as typeof import("../../app/gpt-research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/markitdown-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markitdown-test">> = Specific
  const handler = {} as typeof import("../../app/markitdown-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notes/[id]">> = Specific
  const handler = {} as typeof import("../../app/notes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/org/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/api-keys">> = Specific
  const handler = {} as typeof import("../../app/org/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/org/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/users">> = Specific
  const handler = {} as typeof import("../../app/org/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/productbacklog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productbacklog">> = Specific
  const handler = {} as typeof import("../../app/productbacklog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/api-keys">> = Specific
  const handler = {} as typeof import("../../app/profile/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/research-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research-summary">> = Specific
  const handler = {} as typeof import("../../app/research-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[ws]">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/projects/[projectSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[ws]/projects/[projectSlug]">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/projects/[projectSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[ws]/search">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/visualize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[ws]/visualize">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/visualize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workspaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces">> = Specific
  const handler = {} as typeof import("../../app/workspaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/add-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/add-user">> = Specific
  const handler = {} as typeof import("../../app/api/admin/add-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/check-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/check-sessions">> = Specific
  const handler = {} as typeof import("../../app/api/admin/check-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/check-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/check-users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/check-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organizations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/test-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-auth">> = Specific
  const handler = {} as typeof import("../../app/api/admin/test-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/test-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-session">> = Specific
  const handler = {} as typeof import("../../app/api/admin/test-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent-mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-mcp">> = Specific
  const handler = {} as typeof import("../../app/api/agent-mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/anonymize-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/anonymize-preview">> = Specific
  const handler = {} as typeof import("../../app/api/anonymize-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/debug">> = Specific
  const handler = {} as typeof import("../../app/api/auth/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/claude-tool/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claude-tool">> = Specific
  const handler = {} as typeof import("../../app/api/claude-tool/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug-permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-permissions">> = Specific
  const handler = {} as typeof import("../../app/api/debug-permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/fix-robert-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/fix-robert-access">> = Specific
  const handler = {} as typeof import("../../app/api/debug/fix-robert-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/workspace-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/workspace-access">> = Specific
  const handler = {} as typeof import("../../app/api/debug/workspace-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs">> = Specific
  const handler = {} as typeof import("../../app/api/docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gpt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gpt">> = Specific
  const handler = {} as typeof import("../../app/api/gpt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/invitations/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/invitations/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/keys">> = Specific
  const handler = {} as typeof import("../../app/api/keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/markitdown-test/convert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/markitdown-test/convert">> = Specific
  const handler = {} as typeof import("../../app/api/markitdown-test/convert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp-ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp-ai">> = Specific
  const handler = {} as typeof import("../../app/api/mcp-ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp-hosted/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp-hosted">> = Specific
  const handler = {} as typeof import("../../app/api/mcp-hosted/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp-server/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp-server">> = Specific
  const handler = {} as typeof import("../../app/api/mcp-server/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/documents">> = Specific
  const handler = {} as typeof import("../../app/api/mcp/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/projects">> = Specific
  const handler = {} as typeof import("../../app/api/mcp/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific
  const handler = {} as typeof import("../../app/api/mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/search">> = Specific
  const handler = {} as typeof import("../../app/api/mcp/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/test">> = Specific
  const handler = {} as typeof import("../../app/api/mcp/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mcp/workspaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/workspaces">> = Specific
  const handler = {} as typeof import("../../app/api/mcp/workspaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/api-keys/[keyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/api-keys/[keyId]">> = Specific
  const handler = {} as typeof import("../../app/api/org/api-keys/[keyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api/org/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/invitations">> = Specific
  const handler = {} as typeof import("../../app/api/org/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/users/[userId]/role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/users/[userId]/role">> = Specific
  const handler = {} as typeof import("../../app/api/org/users/[userId]/role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/users/[userId]">> = Specific
  const handler = {} as typeof import("../../app/api/org/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/users/invite-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/users/invite-link">> = Specific
  const handler = {} as typeof import("../../app/api/org/users/invite-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/users/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/users/invite">> = Specific
  const handler = {} as typeof import("../../app/api/org/users/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/org/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/users">> = Specific
  const handler = {} as typeof import("../../app/api/org/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations">> = Specific
  const handler = {} as typeof import("../../app/api/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-db">> = Specific
  const handler = {} as typeof import("../../app/api/test-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-env">> = Specific
  const handler = {} as typeof import("../../app/api/test-env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-password">> = Specific
  const handler = {} as typeof import("../../app/api/test-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces">> = Specific
  const handler = {} as typeof import("../../app/api/workspaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/test-deploy">> = Specific
  const handler = {} as typeof import("../../app/test-deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/context/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/context">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/favorite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/favorite">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/favorite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/rename/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/rename">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/rename/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/[tag]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/[tag]">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/[tag]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/documents/[documentId]/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]/documents">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/[projectSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects/[projectSlug]">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/[projectSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/projects">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/search">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/tags">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/users">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/w/[ws]/api/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/w/[ws]/api/workspace">> = Specific
  const handler = {} as typeof import("../../app/w/[ws]/api/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
